import { Ability } from "../datatype/abilities";
export const ABILITY_LIST: Ability[] = [
  {
    id: '61',
    name: 'HP 10% 업',
    description: '최대 HP가 10% 올라간다',
    type: '1',
    icon: 97,
    size: 3,
  },
  {
    id: '62',
    name: 'HP 20% 업',
    description: '최대 HP가 20% 올라간다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '63',
    name: 'HP 30% 업',
    description: '최대 HP가 30% 올라간다',
    type: '1',
    icon: 97,
    size: 7,
  },
  {
    id: '64',
    name: 'HP 40% 업',
    description: '최대 HP가 40% 올라간다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '66',
    name: '공격력 10% 업',
    description: '공격력이 10% 올라간다',
    type: '1',
    icon: 97,
    size: 3,
  },
  {
    id: '67',
    name: '공격력 20% 업',
    description: '공격력이 20% 올라간다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '68',
    name: '공격력 30% 업',
    description: '공격력이 30% 올라간다',
    type: '1',
    icon: 97,
    size: 7,
  },
  {
    id: '69',
    name: '공격력 40% 업',
    description: '공격력이 40% 올라간다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '71',
    name: '명중율 5% 업',
    description: '명중율이 5% 올라간다',
    type: '1',
    icon: 97,
    size: 3,
  },
  {
    id: '72',
    name: '명중율 10% 업',
    description: '명중율이 10% 올라간다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '73',
    name: '명중율 20% 업',
    description: '명중율이 20% 올라간다',
    type: '1',
    icon: 97,
    size: 9,
  },
  {
    id: '74',
    name: '완전필중',
    description: '반드시 공격이 명중한다',
    type: '1',
    icon: 97,
    size: 12,
  },
  {
    id: '75',
    name: '회심 10%',
    description: '회심율이 10%가 된다',
    type: '1',
    icon: 97,
    size: 4,
  },
  {
    id: '76',
    name: '회심 30%',
    description: '회심율이 30%가 된다',
    type: '1',
    icon: 97,
    size: 8,
  },
  {
    id: '77',
    name: '회심 50%',
    description: '회심율이 50%가 된다',
    type: '1',
    icon: 97,
    size: 12,
  },
  {
    id: '79',
    name: '빈사시 회심 업',
    description: '빈사시, 회심율이 50% 올라간다',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '80',
    name: '빈사시 절대 회심',
    description: '빈사시, 반드시 회심의 일격이 발생한다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '81',
    name: '카운터 10%',
    description: '카운터율이 10%가 된다',
    type: '1',
    icon: 97,
    size: 4,
  },
  {
    id: '82',
    name: '카운터 30%',
    description: '카운터율이 30%가 된다',
    type: '1',
    icon: 97,
    size: 8,
  },
  {
    id: '83',
    name: '카운터 50%',
    description: '카운터율이 50%가 된다',
    type: '1',
    icon: 97,
    size: 12,
  },
  {
    id: '85',
    name: '마법 카운터 10%',
    description: '마법 카운터율이 10%가 된다',
    type: '1',
    icon: 97,
    size: 4,
  },
  {
    id: '86',
    name: '마법 카운터 30%',
    description: '마법 카운터율이 30%가 된다',
    type: '1',
    icon: 97,
    size: 8,
  },
  {
    id: '87',
    name: '마법 카운터 50%',
    description: '마법 카운터율이 50%가 된다',
    type: '1',
    icon: 97,
    size: 12,
  },
  {
    id: '90',
    name: '카운터 공격력 업',
    description: '카운터의 공격력이 올라간다',
    type: '1',
    icon: 97,
    size: 3,
  },
  {
    id: '91',
    name: '카운터 공격력 초업',
    description: '카운터의 공격력이 크게 올라간다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '92',
    name: '점액 카운터',
    description: '물리 공격에 대해서,50%의 확률로 점액 카운터',
    type: '1',
    icon: 97,
    size: 4,
  },
  {
    id: '93',
    name: '소화 점액 카운터',
    description: '물리 공격에 대해서,50%의 확률로 소화 점액 카운터',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '94',
    name: '불굴의 투지',
    description: '빈사시, 모든 능력이 올라간다',
    type: '1',
    icon: 97,
    size: 3,
  },
  {
    id: '95',
    name: '초불굴의 투지',
    description: '빈사시, 모든 능력이 크게 올라간다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '96',
    name: '란불',
    description: '빈사시에 버서크, HP·SP·MP가 턴소회복',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '97',
    name: '워란불',
    description: '빈사시에 버서크, HP·SP·MP가 턴대회복',
    type: '1',
    icon: 97,
    size: 4,
  },
  {
    id: '98',
    name: '고독 이유의 강함',
    description: '전투 불능의 동료수에 응해 모든 능력이 올라간다',
    type: '1',
    icon: 97,
    size: 3,
  },
  {
    id: '99',
    name: '초고독 이유의 강함',
    description: '전투 불능의 동료수에 응해 모든 능력이 크게 올라간다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '100',
    name: '2회 공격',
    description: '통상 공격이 「2회 공격」이 된다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '101',
    name: '3회 공격',
    description: '통상 공격이 「3회 공격」이 된다',
    type: '1',
    icon: 97,
    size: 15,
  },
  {
    id: '102',
    name: '흐트러지고 공격해',
    description: '통상 공격이 「흐트러지고 공격해」(이)가 된다',
    type: '1',
    icon: 97,
    size: 20,
  },
  {
    id: '104',
    name: '전체 공격',
    description: '통상 공격이 「전체 공격」이 된다',
    type: '1',
    icon: 97,
    size: 15,
  },
  {
    id: '105',
    name: '필사격',
    description: '통상 공격이 「필사격」이 된다',
    type: '1',
    icon: 97,
    size: 3,
  },
  {
    id: '106',
    name: '마도격',
    description: '통상 공격이 「마도격」이 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '107',
    name: '리벤지아탁크',
    description: '통상 공격이 「리벤지아탁크」가 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '108',
    name: '드레인 어택',
    description: '통상 공격이 「드레인 어택」이 된다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '109',
    name: '흡마격',
    description: '통상 공격이 「흡마격」이 된다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '110',
    name: '암흑',
    description: '통상 공격이 「암흑」이 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '111',
    name: '엉터리 공격',
    description: '통상 공격이 「엉터리 공격」이 된다',
    type: '1',
    icon: 97,
    size: 1,
  },
  {
    id: '114',
    name: '이도류',
    description: '무기를 양손에 장비 할 수 있다',
    type: '1',
    icon: 97,
    size: 12,
  },
  {
    id: '115',
    name: '인간 특공',
    description: '통상 공격으로 인간에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '116',
    name: '요마 특공',
    description: '통상 공격으로 요마에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '117',
    name: '아인 특공',
    description: '통상 공격으로 아인에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '118',
    name: '음마 특공',
    description: '통상 공격으로 음마에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '119',
    name: '흡혈귀 특공',
    description: '통상 공격으로 흡혈귀에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '120',
    name: '인어 특공',
    description: '통상 공격으로 인어에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '121',
    name: '엘프 특공',
    description: '통상 공격으로 엘프에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '122',
    name: '요정 특공',
    description: '통상 공격으로 요정에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '123',
    name: '슬라임 특공',
    description: '통상 공격으로 슬라임에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '124',
    name: '마수 특공',
    description: '통상 공격으로 마수에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '125',
    name: '요호 특공',
    description: '통상 공격으로 요호에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '126',
    name: '라미아 특공',
    description: '통상 공격으로 라미아에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '127',
    name: '스큐라 특공',
    description: '통상 공격으로 스큐라에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '128',
    name: '하피 특공',
    description: '통상 공격으로 하피에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '129',
    name: '용특공',
    description: '통상 공격으로 드래곤에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '130',
    name: '육서종 특공',
    description: '통상 공격으로 육서종에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '131',
    name: '해서종 특공',
    description: '통상 공격으로 해서종에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '132',
    name: '충 특공',
    description: '통상 공격으로 벌레에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '133',
    name: '식물 특공',
    description: '통상 공격으로 식물에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '134',
    name: '좀비 특공',
    description: '통상 공격으로 좀비에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '135',
    name: '고스트 특공',
    description: '통상 공격으로 고스트에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '136',
    name: '돌 특공',
    description: '통상 공격으로 돌에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '137',
    name: '키메라 특공',
    description: '통상 공격으로 키메라에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '138',
    name: '천사 특공',
    description: '통상 공격으로 천사에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '139',
    name: '거체 특공',
    description: '통상 공격으로 거체의 적에게 주는 데미지가 1.5배가 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '140',
    name: '통상 공격 불길 속성',
    description: '통상 공격이 불길 속성이 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '141',
    name: '통상 공격 얼음 속성',
    description: '통상 공격이 얼음 속성이 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '142',
    name: '통상 공격 번개속성',
    description: '통상 공격이 번개 속성이 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '143',
    name: '통상 공격 바람 속성',
    description: '통상 공격이 바람 속성이 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '144',
    name: '통상 공격 흙 속성',
    description: '통상 공격이 흙 속성이 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '145',
    name: '통상 공격 물 속성',
    description: '통상 공격이 물 속성이 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '146',
    name: '통상 공격 성 속성',
    description: '통상 공격이 성속성이 된다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '147',
    name: '통상 공격 어둠 속성',
    description: '통상 공격이 어둠 속성이 된다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '148',
    name: '통상 공격 음파 속성',
    description: '통상 공격이 음파 속성이 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '149',
    name: '통상 공격 바이오 속성',
    description: '통상 공격이 바이오 속성이 된다',
    type: '1',
    icon: 97,
    size: 6,
  },
  {
    id: '150',
    name: '통상 공격 쾌락 속성',
    description: '통상 공격이 쾌락 속성이 된다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '151',
    name: '물리 부스터',
    description: '물리 데미지가 15% 올라간다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '152',
    name: '물리 하이 부스터',
    description: '물리 데미지가 30% 올라간다',
    type: '1',
    icon: 97,
    size: 20,
  },
  {
    id: '154',
    name: '종족 특공 부스터',
    description: '종족 특공 데미지가 30% 올라간다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '155',
    name: '종족 특공 하이 부스터',
    description: '종족 특공 데미지가 50% 올라간다',
    type: '1',
    icon: 97,
    size: 20,
  },
  {
    id: '157',
    name: '통상 공격 부스터',
    description: '통상 공격의 데미지가 2배가 된다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '158',
    name: '통상 공격 하이 부스터',
    description: '통상 공격의 데미지가 3배가 된다',
    type: '1',
    icon: 97,
    size: 20,
  },
  {
    id: '160',
    name: '단검 부스터',
    description: '단검 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '161',
    name: '단검 하이 부스터',
    description: '단검 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '1',
    icon: 97,
    size: 20,
  },
  {
    id: '163',
    name: '검 부스터',
    description: '검 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '164',
    name: '검 하이 부스터',
    description: '검 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '1',
    icon: 97,
    size: 20,
  },
  {
    id: '166',
    name: '첨검 부스터',
    description: '첨검 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '167',
    name: '첨검 하이 부스터',
    description: '첨검 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '1',
    icon: 97,
    size: 20,
  },
  {
    id: '169',
    name: '창 부스터',
    description: '창 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '170',
    name: '창 하이 부스터',
    description: '창 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '1',
    icon: 97,
    size: 20,
  },
  {
    id: '172',
    name: '도 부스터',
    description: '도 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '173',
    name: '도 하이 부스터',
    description: '도 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '1',
    icon: 97,
    size: 20,
  },
  {
    id: '175',
    name: '닌자도 부스터',
    description: '닌자도 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '176',
    name: '닌자도 하이 부스터',
    description: '닌자도 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '1',
    icon: 97,
    size: 20,
  },
  {
    id: '178',
    name: '주먹 부스터',
    description: '주먹 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '179',
    name: '주먹 하이 부스터',
    description: '주먹 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '1',
    icon: 97,
    size: 20,
  },
  {
    id: '181',
    name: '이빨 부스터',
    description: '이빨 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '182',
    name: '이빨 하이 부스터',
    description: '이빨 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '1',
    icon: 97,
    size: 20,
  },
  {
    id: '184',
    name: '도끼 부스터',
    description: '도끼 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '185',
    name: '도끼 하이 부스터',
    description: '도끼 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '1',
    icon: 97,
    size: 20,
  },
  {
    id: '187',
    name: '곤봉 부스터',
    description: '곤봉 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '188',
    name: '곤봉 하이 부스터',
    description: '곤봉 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '1',
    icon: 97,
    size: 20,
  },
  {
    id: '190',
    name: '낫 부스터',
    description: '낫 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '191',
    name: '낫 하이 부스터',
    description: '낫 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '1',
    icon: 97,
    size: 20,
  },
  {
    id: '193',
    name: '활 부스터',
    description: '활 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '194',
    name: '활 하이 부스터',
    description: '활 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '1',
    icon: 97,
    size: 20,
  },
  {
    id: '196',
    name: '채찍 부스터',
    description: '채찍 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '197',
    name: '채찍 하이 부스터',
    description: '채찍 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '1',
    icon: 97,
    size: 20,
  },
  {
    id: '199',
    name: '부메랑 부스터',
    description: '부메랑 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '200',
    name: '부메랑 하이 부스터',
    description: '부메랑 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '1',
    icon: 97,
    size: 20,
  },
  {
    id: '202',
    name: '철구 부스터',
    description: '철구 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '203',
    name: '철구 하이 부스터',
    description: '철구 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '1',
    icon: 97,
    size: 20,
  },
  {
    id: '205',
    name: '부채 부스터',
    description: '부채 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '206',
    name: '부채 하이 부스터',
    description: '부채 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '1',
    icon: 97,
    size: 20,
  },
  {
    id: '208',
    name: '총 부스터',
    description: '총 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '1',
    icon: 97,
    size: 10,
  },
  {
    id: '209',
    name: '총 하이 부스터',
    description: '총 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '1',
    icon: 97,
    size: 20,
  },
  {
    id: '211',
    name: '「단검」장비 가능',
    description: '「단검」이 장비 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '212',
    name: '「검」장비 가능',
    description: '「검」 「기사검」이 장비 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '213',
    name: '「거검」장비 가능',
    description: '「거검」이 장비 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '214',
    name: '「첨검」장비 가능',
    description: '「첨검」이 장비 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '215',
    name: '「창」장비 가능',
    description: '「창」 「중창」이 장비 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '216',
    name: '「도」장비 가능',
    description: '「도」가 장비 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '217',
    name: '「닌자도」장비 가능',
    description: '「닌자도」가 장비 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '218',
    name: '「주먹」장비 가능',
    description: '「주먹」이 장비 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '219',
    name: '「이빨」장비 가능',
    description: '「이빨」이 장비 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '220',
    name: '「도끼」장비 가능',
    description: '「도끼」가 장비 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '221',
    name: '「곤봉」장비 가능',
    description: '「곤봉」이 장비 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '222',
    name: '「낫」장비 가능',
    description: '「낫」이 장비 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '223',
    name: '「활」장비 가능',
    description: '「활」이 장비 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '224',
    name: '「채찍」장비 가능',
    description: '「채찍」이 장비 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '225',
    name: '「부메랑」장비 가능',
    description: '「부메랑」이 장비 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '226',
    name: '「철구」장비 가능',
    description: '「철구」가 장비 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '227',
    name: '「부채」장비 가능',
    description: '「부채」가 장비 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '228',
    name: '「총」장비 가능',
    description: '「총」이 장비 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '229',
    name: '「단검 기술」사용 가능',
    description: '「단검 기술」이 사용 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '230',
    name: '「검 기술」사용 가능',
    description: '「검 기술」이 사용 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '231',
    name: '「첨검 기술」사용 가능',
    description: '「첨검 기술」이 사용 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '232',
    name: '「도 기술」사용 가능',
    description: '「도 기술」이 사용 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '233',
    name: '「창 기술」사용 가능',
    description: '「창 기술」이 사용 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '234',
    name: '「도끼 기술」사용 가능',
    description: '「도끼 기술」이 사용 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '235',
    name: '「곤봉 기술」사용 가능',
    description: '「곤봉 기술」이 사용 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '236',
    name: '「낫 기술」사용 가능',
    description: '「낫 기술」이 사용 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '237',
    name: '「활 기술」사용 가능',
    description: '「활 기술」이 사용 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '238',
    name: '「채찍 기술」사용 가능',
    description: '「채찍 기술」이 사용 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '239',
    name: '「투척 기술」사용 가능',
    description: '「투척 기술」이 사용 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '240',
    name: '「철구 기술」사용 가능',
    description: '「철구 기술」이 사용 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '241',
    name: '「부채 기술」사용 가능',
    description: '「부채 기술」이 사용 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '242',
    name: '「총 기술」사용 가능',
    description: '「총 기술」이 사용 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '243',
    name: '「다무기 기술」사용 가능',
    description: '「다무기 기술」이 사용 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '244',
    name: '「격투」사용 가능',
    description: '「격투」가 사용 가능하게 된다',
    type: '1',
    icon: 97,
    size: 5,
  },
  {
    id: '246',
    name: '겹의 주먹',
    description: '「격투」의 위력이 공격력에게만 의존한다',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '247',
    name: '약의 주먹',
    description: '「격투」의 위력이 민첩성에게만 의존한다',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '248',
    name: '테크니컬 나이프',
    description: '「단검 기술」의 위력이 손재주에게만 의존한다',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '249',
    name: '절의 칼날',
    description: '「도 기술」의 위력이 힘에게만 의존한다',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '250',
    name: '섬의 칼날',
    description: '「도 기술」의 위력이 손재주에게만 의존한다',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '251',
    name: '강의 창',
    description: '「창 기술」의 위력이 힘에게만 의존한다',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '252',
    name: '하늘의 창',
    description: '「창 기술」의 위력이 민첩성에게만 의존한다',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '253',
    name: '유려주먹법',
    description: '「격투」의 위력으로 공격력 대신에 손재주가 이용된다',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '254',
    name: '마기레이피아',
    description: '「첨검 기술」의 위력으로 공격력 대신에 마력이 이용된다',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '255',
    name: '방호의 철구',
    description: '「철구 기술」의 위력으로 공격력 대신에 방어력이 이용된다',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '256',
    name: '정신의 철구',
    description: '「철구 기술」의 위력으로 공격력 대신에 정신력이 이용된다',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '257',
    name: '기용의 철구',
    description: '「철구 기술」의 위력으로 공격력 대신에 손재주가 이용된다',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '258',
    name: '테크니카르위프',
    description: '「채찍 기술」의 위력이 손재주에게만 의존한다',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '259',
    name: '마지카르위프',
    description: '「채찍 기술」의 위력으로 공격력 대신에 마력이 이용된다',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '260',
    name: '마인드위프',
    description: '「채찍 기술」의 위력으로 공격력 대신에 정신력이 이용된다',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '261',
    name: '테크니컬 부메랑',
    description: '「투척 기술」의 위력이 손재주에게만 의존한다',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '262',
    name: '가드 부메랑',
    description: '「투척 기술」의 위력으로 공격력 대신에 방어력이 이용된다',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '263',
    name: '마인드 부메랑',
    description: '「투척 기술」의 위력으로 공격력 대신에 정신력이 이용된다',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '264',
    name: '매직컬 소드',
    description: '「검 기술」의 위력이 마력에게만 의존한다',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '265',
    name: '테크니컬 소드',
    description: '「검 기술」의 위력이 손재주에게만 의존한다',
    type: '1',
    icon: 97,
    size: 2,
  },
  {
    id: '268',
    name: 'SP 10% 업',
    description: '최대 SP가 10% 올라간다',
    type: '2',
    icon: 102,
    size: 3,
  },
  {
    id: '269',
    name: 'SP 20% 업',
    description: '최대 SP가 20% 올라간다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '270',
    name: 'SP 30% 업',
    description: '최대 SP가 30% 올라간다',
    type: '2',
    icon: 102,
    size: 7,
  },
  {
    id: '271',
    name: 'SP 40% 업',
    description: '최대 SP가 40% 올라간다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '273',
    name: '민첩성 10% 업',
    description: '민첩성이 10% 올라간다',
    type: '2',
    icon: 102,
    size: 3,
  },
  {
    id: '274',
    name: '민첩성 20% 업',
    description: '민첩성이 20% 올라간다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '275',
    name: '민첩성 30% 업',
    description: '민첩성이 30% 올라간다',
    type: '2',
    icon: 102,
    size: 7,
  },
  {
    id: '276',
    name: '민첩성 40% 업',
    description: '민첩성이 40% 올라간다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '278',
    name: '손재주 10% 업',
    description: '손재주가 10% 올라간다',
    type: '2',
    icon: 102,
    size: 3,
  },
  {
    id: '279',
    name: '손재주 20% 업',
    description: '손재주가 20% 올라간다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '280',
    name: '손재주 30% 업',
    description: '손재주가 30% 올라간다',
    type: '2',
    icon: 102,
    size: 7,
  },
  {
    id: '281',
    name: '손재주 40% 업',
    description: '손재주가 40% 올라간다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '283',
    name: 'SP소비 3/4',
    description: '스킬 사용시의 SP소비가 3/4가 된다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '284',
    name: 'SP소비 1/2',
    description: '스킬 사용시의 SP소비가 반이 된다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '285',
    name: 'SP소비 1/4',
    description: '스킬 사용시의 SP소비가 1/4가 된다',
    type: '2',
    icon: 102,
    size: 30,
  },
  {
    id: '287',
    name: '언제라도 탈취한다',
    description: '통상 공격이 「탈취한다」(이)가 된다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '288',
    name: '생명보험',
    description: '전투 불능시, 골드를 획득',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '289',
    name: '쭉 맞고 이득',
    description: '받은 데미지에 응해 골드를 획득',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '290',
    name: '최후의 신탁',
    description: '전투 불능시, 아이템을 입수',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '291',
    name: '라스트 슬롯',
    description: '전투 불능시, 보다 좋은 아이템을 입수',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '292',
    name: '파이널 찬스',
    description: '전투 불능시, 레어 아이템을 입수',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '293',
    name: '유언',
    description: '전투 불능시, 동료 전원의 능력이 대업',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '294',
    name: '길동무 BC병기',
    description: '전투 불능시, 맹독을 흩뿌린다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '295',
    name: '말기의 봉사',
    description: '전투 불능시, 아군의 전체의 HP·MP·SP를 대회복',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '296',
    name: '메이드의 땅산',
    description: '전투 불능시, 아군의 전체의 HP·MP·SP를 전회복',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '297',
    name: '속박되고 메이드',
    description: '전투 개시시에 어둠·마비·침묵, 획득 경험치 2배',
    type: '2',
    icon: 102,
    size: 1,
  },
  {
    id: '298',
    name: '성자 순교',
    description: '전투 불능시, 아군 전체의 HP를 전회복 및 완전 소생',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '299',
    name: '성자옥쇄',
    description: '전투 불능시, 적 전체에 화속성의 대데미지',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '300',
    name: '만나자마자의 우렁찬 외침',
    description: '전투 개시시, 적 전체를 스턴 시키는 우렁찬 외침을 일정 확률로 발한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '302',
    name: '개막 깜짝 상자',
    description: '전투 개시시, 적 전체를 놀래켜 스턴 시킨다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '304',
    name: '통상 공격 즉사·저',
    description: '통상 공격시, 적을 저확률로 즉사시킨다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '305',
    name: '통상 공격 즉사·중',
    description: '통상 공격시, 적을 중확률로 즉사시킨다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '307',
    name: '통상 공격 승천·저',
    description: '통상 공격시, 적을 저확률로 승천 시킨다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '308',
    name: '통상 공격 승천·중',
    description: '통상 공격시, 적을 중확률로 승천 시킨다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '310',
    name: '통상 공격 절정·저',
    description: '통상 공격시, 적을 저확률로 절정 시킨다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '311',
    name: '통상 공격 절정·중',
    description: '통상 공격시, 적을 중확률로 절정 시킨다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '313',
    name: '통상 공격독·저',
    description: '통상 공격시, 적을 저확률로 독상태로 한다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '314',
    name: '통상 공격독·중',
    description: '통상 공격시, 적을 중확률로 독상태로 한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '315',
    name: '통상 공격독·고',
    description: '통상 공격시, 적을 고확률로 독상태로 한다',
    type: '2',
    icon: 102,
    size: 15,
  },
  {
    id: '316',
    name: '통상 공격 어둠·저',
    description: '통상 공격시, 적을 저확률로 어둠 상태로 한다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '317',
    name: '통상 공격 어둠·중',
    description: '통상 공격시, 적을 중확률로 어둠 상태로 한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '319',
    name: '통상 공격 침묵·저',
    description: '통상 공격시, 적을 저확률로 침묵 상태로 한다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '320',
    name: '통상 공격 침묵·중',
    description: '통상 공격시, 적을 중확률로 침묵 상태로 한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '321',
    name: '통상 공격 침묵·고',
    description: '통상 공격시, 적을 고확률로 침묵 상태로 한다',
    type: '2',
    icon: 102,
    size: 15,
  },
  {
    id: '322',
    name: '통상 공격 혼란·저',
    description: '통상 공격시, 적을 저확률로 혼란 상태로 한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '323',
    name: '통상 공격 혼란·중',
    description: '통상 공격시, 적을 중확률로 혼란 상태로 한다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '325',
    name: '통상 공격 수면·저',
    description: '통상 공격시, 적을 저확률로 수면 상태로 한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '326',
    name: '통상 공격 수면·중',
    description: '통상 공격시, 적을 중확률로 수면 상태로 한다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '328',
    name: '통상 공격 마비·저',
    description: '통상 공격시, 적을 저확률로 마비 상태로 한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '329',
    name: '통상 공격 마비·중',
    description: '통상 공격시, 적을 중확률로 마비 상태로 한다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '331',
    name: '통상 공격 반·저',
    description: '통상 공격시, 적을 저확률로 반 상태로 한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '332',
    name: '통상 공격 반·중',
    description: '통상 공격시, 적을 중확률로 반 상태로 한다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '334',
    name: '통상 공격 프리즈·저',
    description: '통상 공격시, 적을 저확률로 프리즈 상태로 한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '335',
    name: '통상 공격 프리즈·중',
    description: '통상 공격시, 적을 중확률로 프리즈 상태로 한다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '337',
    name: '통상 공격 쇼크·저',
    description: '통상 공격시, 적을 저확률로 쇼크 상태로 한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '338',
    name: '통상 공격 쇼크·중',
    description: '통상 공격시, 적을 중확률로 쇼크 상태로 한다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '339',
    name: '통상 공격 쇼크·고',
    description: '통상 공격시, 적을 고확률로 쇼크 상태로 한다',
    type: '2',
    icon: 102,
    size: 30,
  },
  {
    id: '340',
    name: '통상 공격 슬로우·저',
    description: '통상 공격시, 적을 저확률로 슬로우 상태로 한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '341',
    name: '통상 공격 슬로우·중',
    description: '통상 공격시, 적을 중확률로 슬로우 상태로 한다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '342',
    name: '통상 공격 슬로우·고',
    description: '통상 공격시, 적을 고확률로 슬로우 상태로 한다',
    type: '2',
    icon: 102,
    size: 30,
  },
  {
    id: '343',
    name: '통상 공격 스톱·저',
    description: '통상 공격시, 적을 저확률로 스톱 상태로 한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '344',
    name: '통상 공격 스톱·중',
    description: '통상 공격시, 적을 중확률로 스톱 상태로 한다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '345',
    name: '통상 공격 스톱·고',
    description: '통상 공격시, 적을 고확률로 스톱 상태로 한다',
    type: '2',
    icon: 102,
    size: 30,
  },
  {
    id: '346',
    name: '통상 공격 미니맘·저',
    description: '통상 공격시, 적을 저확률로 미니맘 상태로 한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '347',
    name: '통상 공격 미니맘·중',
    description: '통상 공격시, 적을 중확률로 미니맘 상태로 한다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '349',
    name: '통상 공격 좀비·저',
    description: '통상 공격시, 적을 저확률로 좀비 상태로 한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '350',
    name: '통상 공격 좀비·중',
    description: '통상 공격시, 적을 중확률로 좀비 상태로 한다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '352',
    name: '통상 공격 석화·저',
    description: '통상 공격시, 적을 저확률로 석화 상태 한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '353',
    name: '통상 공격 석화·중',
    description: '통상 공격시, 적을 중확률로 석화 상태 한다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '355',
    name: '통상 공격 소화·저',
    description: '통상 공격시, 적을 저확률로 소화 상태로 한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '356',
    name: '통상 공격 소화·중',
    description: '통상 공격시, 적을 중확률로 소화 상태로 한다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '358',
    name: '통상 공격 스턴·저',
    description: '통상 공격시, 적을 저확률로 스턴 상태로 한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '359',
    name: '통상 공격 스턴·중',
    description: '통상 공격시, 적을 중확률로 스턴 상태로 한다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '361',
    name: '통상 공격 미끈미끈·저',
    description: '통상 공격시, 적을 저확률로 미끈미끈 상태로 한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '362',
    name: '통상 공격 미끈미끈·중',
    description: '통상 공격시, 적을 중확률로 미끈미끈 상태로 한다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '364',
    name: '통상 공격 민감·저',
    description: '통상 공격시, 적을 저확률로 민감 상태로 한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '365',
    name: '통상 공격 민감·중',
    description: '통상 공격시, 적을 중확률로 민감 상태로 한다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '367',
    name: '통상 공격 황홀·저',
    description: '통상 공격시, 적을 저확률로 황홀 상태로 한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '368',
    name: '통상 공격 황홀·중',
    description: '통상 공격시, 적을 중확률로 황홀 상태로 한다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '370',
    name: '통상 공격 유혹·저',
    description: '통상 공격시, 적을 저확률로 유혹 상태로 한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '371',
    name: '통상 공격 유혹·중',
    description: '통상 공격시, 적을 중확률로 유혹 상태로 한다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '373',
    name: '통상 공격 실금·저',
    description: '통상 공격시, 적을 저확률로 실금 상태로 한다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '374',
    name: '통상 공격 실금·중',
    description: '통상 공격시, 적을 중확률로 실금 상태로 한다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '376',
    name: '하프 부스터',
    description: '하프 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '377',
    name: '하프 하이 부스터',
    description: '하프 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '379',
    name: '부엌칼 부스터',
    description: '부엌칼 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '380',
    name: '부엌칼 하이 부스터',
    description: '부엌칼 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '382',
    name: '주판 부스터',
    description: '주판 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '383',
    name: '주판 하이 부스터',
    description: '주판 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '384',
    name: '주판 액스 부스터',
    description: '주판 장비시, 그 무기에 의한 데미지가 50% 올라간다',
    type: '2',
    icon: 102,
    size: 30,
  },
  {
    id: '385',
    name: '메스 부스터',
    description: '메스 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '386',
    name: '메스 하이 부스터',
    description: '메스 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '387',
    name: '메스 액스 부스터',
    description: '메스 장비시, 그 무기에 의한 데미지가 50% 올라간다',
    type: '2',
    icon: 102,
    size: 30,
  },
  {
    id: '388',
    name: '카드 부스터',
    description: '카드 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '389',
    name: '카드 하이 부스터',
    description: '카드 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '390',
    name: '카드 액스 부스터',
    description: '카드 장비시, 그 무기에 의한 데미지가 50% 올라간다',
    type: '2',
    icon: 102,
    size: 30,
  },
  {
    id: '391',
    name: '접시 부스터',
    description: '접시 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '392',
    name: '접시 하이 부스터',
    description: '접시 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '393',
    name: '접시 액스 부스터',
    description: '접시 장비시, 그 무기에 의한 데미지가 50% 올라간다',
    type: '2',
    icon: 102,
    size: 30,
  },
  {
    id: '394',
    name: '음구 부스터',
    description: '음구 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '395',
    name: '음구 하이 부스터',
    description: '음구 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '397',
    name: '마키나 부스터',
    description: '「마키나」에 의한 데미지가 15% 올라간다',
    type: '2',
    icon: 102,
    size: 10,
  },
  {
    id: '398',
    name: '마키나 하이 부스터',
    description: '「마키나」에 의한 데미지가 30% 올라간다',
    type: '2',
    icon: 102,
    size: 20,
  },
  {
    id: '400',
    name: '「하프」장비 가능',
    description: '「하프」가 장비 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '401',
    name: '「부엌칼」장비 가능',
    description: '「부엌칼」이 장비 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '402',
    name: '「주판」장비 가능',
    description: '「주판」이 장비 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '403',
    name: '「메스」장비 가능',
    description: '「메스」가 장비 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '404',
    name: '「 카드」장비 가능',
    description: '「 카드」가 장비 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '405',
    name: '「접시」장비 가능',
    description: '「접시」가 장비 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '406',
    name: '「음구」장비 가능',
    description: '「음구」가 장비 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '407',
    name: '「도적 기술」사용 가능',
    description: '「도적 기술」이 사용 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '408',
    name: '「인술」사용 가능',
    description: '「인술」이 사용 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '409',
    name: '「해적 기술」사용 가능',
    description: '「해적 기술」이 사용 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '410',
    name: '「상인 기술」사용 가능',
    description: '「상인 기술」이 사용 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '411',
    name: '「EX아이템」사용 가능',
    description: '「EX아이템」이 사용 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '412',
    name: '「오라클」사용 가능',
    description: '「오라클」이 사용 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '413',
    name: '「춤」사용 가능',
    description: '「춤」이 사용 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '414',
    name: '「노래」사용 가능',
    description: '「노래」가 사용 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '415',
    name: '「이야기하기」사용 가능',
    description: '「이야기하기」가 사용 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '416',
    name: '「마키나」사용 가능',
    description: '「마키나」가 사용 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '417',
    name: '「요리」사용 가능',
    description: '「요리」가 사용 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '418',
    name: '「의술」사용 가능',
    description: '「의술」이 사용 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '419',
    name: '「봉사」사용 가능',
    description: '「봉사」가 사용 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '420',
    name: '「왕 기술」사용 가능',
    description: '「왕 기술」이 사용 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '421',
    name: '「용사 기술」사용 가능',
    description: '「용사 기술」이 사용 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '422',
    name: '「음 기술」사용 가능',
    description: '「음 기술」이 사용 가능하게 된다',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '423',
    name: '듀얼영혼',
    description: '「오라클」밖에 사용 할 수 없지만, 2회 연속 발동',
    type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '424',
    name: '입 끝 말도 잘하고 솜씨도 좋음',
    description: '「이야기하기」밖에 사용 할 수 없지만, 소비 SP가 저하 회피율과 마법 회피율이 30 % 업',
type: '2',
    icon: 102,
    size: 5,
  },
  {
    id: '446',
    name: 'MP 10% 업',
    description: '최대 MP가 10% 올라간다',
    type: '3',
    icon: 100,
    size: 3,
  },
  {
    id: '447',
    name: 'MP 20% 업',
    description: '최대 MP가 20% 올라간다',
    type: '3',
    icon: 100,
    size: 5,
  },
  {
    id: '448',
    name: 'MP 30% 업',
    description: '최대 MP가 30% 올라간다',
    type: '3',
    icon: 100,
    size: 7,
  },
  {
    id: '449',
    name: 'MP 40% 업',
    description: '최대 MP가 40% 올라간다',
    type: '3',
    icon: 100,
    size: 10,
  },
  {
    id: '451',
    name: '마력 10% 업',
    description: '마력이 10% 올라간다',
    type: '3',
    icon: 100,
    size: 3,
  },
  {
    id: '452',
    name: '마력 20% 업',
    description: '마력이 20% 올라간다',
    type: '3',
    icon: 100,
    size: 5,
  },
  {
    id: '453',
    name: '마력 30% 업',
    description: '마력이 30% 올라간다',
    type: '3',
    icon: 100,
    size: 7,
  },
  {
    id: '454',
    name: '마력 40% 업',
    description: '마력이 40% 올라간다',
    type: '3',
    icon: 100,
    size: 10,
  },
  {
    id: '456',
    name: 'MP소비 3/4',
    description: '스킬 사용시의 MP소비가 3/4가 된다',
    type: '3',
    icon: 100,
    size: 10,
  },
  {
    id: '457',
    name: 'MP소비 1/2',
    description: '스킬 사용시의 MP소비가 반이 된다',
    type: '3',
    icon: 100,
    size: 20,
  },
  {
    id: '458',
    name: 'MP소비 1/4',
    description: '스킬 사용시의 MP소비가 1/4가 된다',
    type: '3',
    icon: 100,
    size: 30,
  },
  {
    id: '460',
    name: '라이트 매직',
    description: '마법의 소비 MP가 반이 되지만, 마력도 반이 된다',
    type: '3',
    icon: 100,
    size: 5,
  },
  {
    id: '461',
    name: '헤비마직크',
    description: '마법의 소비 MP가 2배가 되지만, 마력은 1.5배가 된다',
    type: '3',
    icon: 100,
    size: 10,
  },
  {
    id: '462',
    name: '마도변환 장치',
    description: '마력과 정신력이 1.5배가 되지만, 힘과 방어력이 반이 된다',
    type: '3',
    icon: 100,
    size: 10,
  },
  {
    id: '463',
    name: '마도리후레크트',
    description: '마법을 반사하지만, 받는 물리 데미지가 2배가 된다',
    type: '3',
    icon: 100,
    size: 6,
  },
  {
    id: '464',
    name: '상시 매직 커텐',
    description: '받은 데미지에 응해 MP가 회복',
    type: '3',
    icon: 100,
    size: 20,
  },
  {
    id: '465',
    name: '요정의 제물',
    description: '사망시, 랜덤 소환',
    type: '3',
    icon: 100,
    size: 10,
  },
  {
    id: '467',
    name: '쾌락 부스터',
    description: '쾌락 속성의 데미지가 15% 올라간다',
    type: '3',
    icon: 100,
    size: 8,
  },
  {
    id: '468',
    name: '쾌락 하이 부스터',
    description: '쾌락 속성의 데미지가 30% 올라간다',
    type: '3',
    icon: 100,
    size: 16,
  },
  {
    id: '470',
    name: '불길 부스터',
    description: '염 속성의 데미지가 15% 올라간다',
    type: '3',
    icon: 100,
    size: 8,
  },
  {
    id: '471',
    name: '불길 하이 부스터',
    description: '염 속성의 데미지가 30% 올라간다',
    type: '3',
    icon: 100,
    size: 16,
  },
  {
    id: '473',
    name: '얼음 부스터',
    description: '얼음 속성의 데미지가 15% 올라간다',
    type: '3',
    icon: 100,
    size: 8,
  },
  {
    id: '474',
    name: '얼음 하이 부스터',
    description: '얼음 속성의 데미지가 30% 올라간다',
    type: '3',
    icon: 100,
    size: 16,
  },
  {
    id: '476',
    name: '번개 부스터',
    description: '번개 속성의 데미지가 15% 올라간다',
    type: '3',
    icon: 100,
    size: 8,
  },
  {
    id: '477',
    name: '번개 하이 부스터',
    description: '번개 속성의 데미지가 30% 올라간다',
    type: '3',
    icon: 100,
    size: 16,
  },
  {
    id: '479',
    name: '바람 부스터',
    description: '풍속성의 데미지가 15% 올라간다',
    type: '3',
    icon: 100,
    size: 8,
  },
  {
    id: '480',
    name: '바람 하이 부스터',
    description: '풍속성의 데미지가 30% 올라간다',
    type: '3',
    icon: 100,
    size: 16,
  },
  {
    id: '482',
    name: '흙 부스터',
    description: '흙 속성의 데미지가 15% 올라간다',
    type: '3',
    icon: 100,
    size: 8,
  },
  {
    id: '483',
    name: '흙 하이 부스터',
    description: '흙 속성의 데미지가 30% 올라간다',
    type: '3',
    icon: 100,
    size: 16,
  },
  {
    id: '485',
    name: '물 부스터',
    description: '물 속성의 데미지가 15% 올라간다',
    type: '3',
    icon: 100,
    size: 8,
  },
  {
    id: '486',
    name: '물 하이 부스터',
    description: '물 속성의 데미지가 30% 올라간다',
    type: '3',
    icon: 100,
    size: 16,
  },
  {
    id: '488',
    name: '성 부스터',
    description: '성속성의 데미지가 15% 올라간다',
    type: '3',
    icon: 100,
    size: 8,
  },
  {
    id: '489',
    name: '성 하이 부스터',
    description: '성속성의 데미지가 30% 올라간다',
    type: '3',
    icon: 100,
    size: 16,
  },
  {
    id: '491',
    name: '어둠 부스터',
    description: '어둠 속성의 데미지가 15% 올라간다',
    type: '3',
    icon: 100,
    size: 8,
  },
  {
    id: '492',
    name: '어둠 하이 부스터',
    description: '어둠 속성의 데미지가 30% 올라간다',
    type: '3',
    icon: 100,
    size: 16,
  },
  {
    id: '494',
    name: '음파 부스터',
    description: '음파 속성의 데미지가 15% 올라간다',
    type: '3',
    icon: 100,
    size: 8,
  },
  {
    id: '495',
    name: '음파 하이 부스터',
    description: '음파 속성의 데미지가 30% 올라간다',
    type: '3',
    icon: 100,
    size: 16,
  },
  {
    id: '497',
    name: '바이오 부스터',
    description: '바이오 속성의 데미지가 15% 올라간다',
    type: '3',
    icon: 100,
    size: 8,
  },
  {
    id: '498',
    name: '바이오 하이 부스터',
    description: '바이오 속성의 데미지가 30% 올라간다',
    type: '3',
    icon: 100,
    size: 16,
  },
  {
    id: '500',
    name: '회복 부스터',
    description: '회복 속성의 효과가 15% 올라간다',
    type: '3',
    icon: 100,
    size: 8,
  },
  {
    id: '501',
    name: '회복 하이 부스터',
    description: '회복 속성의 효과가 30% 올라간다',
    type: '3',
    icon: 100,
    size: 16,
  },
  {
    id: '502',
    name: '회복 액스 부스터',
    description: '회복 속성의 효과가 50% 올라간다',
    type: '3',
    icon: 100,
    size: 24,
  },
  {
    id: '503',
    name: '지팡이 부스터',
    description: '지팡이 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '3',
    icon: 100,
    size: 10,
  },
  {
    id: '504',
    name: '지팡이 하이 부스터',
    description: '지팡이 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '3',
    icon: 100,
    size: 20,
  },
  {
    id: '506',
    name: '로드 부스터',
    description: '로드 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '3',
    icon: 100,
    size: 10,
  },
  {
    id: '507',
    name: '로드 하이 부스터',
    description: '로드 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '3',
    icon: 100,
    size: 20,
  },
  {
    id: '509',
    name: '마도서 부스터',
    description: '마도서 장비시, 그 무기에 의한 데미지가 15% 올라간다',
    type: '3',
    icon: 100,
    size: 10,
  },
  {
    id: '510',
    name: '마도서 하이 부스터',
    description: '마도서 장비시, 그 무기에 의한 데미지가 30% 올라간다',
    type: '3',
    icon: 100,
    size: 20,
  },
  {
    id: '512',
    name: '「마도검」장비 가능',
    description: '「마도검」이 장비 가능하게 된다',
    type: '3',
    icon: 100,
    size: 5,
  },
  {
    id: '513',
    name: '「지팡이」장비 가능',
    description: '「지팡이」가 장비 가능하게 된다',
    type: '3',
    icon: 100,
    size: 5,
  },
  {
    id: '514',
    name: '「로드」장비 가능',
    description: '「로드」가 장비 가능하게 된다',
    type: '3',
    icon: 100,
    size: 5,
  },
  {
    id: '515',
    name: '「마도서」장비 가능',
    description: '「마도서」가 장비 가능하게 된다',
    type: '3',
    icon: 100,
    size: 5,
  },
  {
    id: '516',
    name: '「백마법」사용 가능',
    description: '「백마법」이 사용 가능하게 된다',
    type: '3',
    icon: 100,
    size: 5,
  },
  {
    id: '517',
    name: '「흑마법」사용 가능',
    description: '「흑마법」이 사용 가능하게 된다',
    type: '3',
    icon: 100,
    size: 5,
  },
  {
    id: '518',
    name: '「시마법」사용 가능',
    description: '「시마법」이 사용 가능하게 된다',
    type: '3',
    icon: 100,
    size: 5,
  },
  {
    id: '519',
    name: '「소환」사용 가능',
    description: '「소환」이 사용 가능하게 된다',
    type: '3',
    icon: 100,
    size: 5,
  },
  {
    id: '520',
    name: '「성 기술」사용 가능',
    description: '「성 기술」이 사용 가능하게 된다',
    type: '3',
    icon: 100,
    size: 5,
  },
  {
    id: '521',
    name: '「어둠 기술」사용 가능',
    description: '「어둠 기술」이 사용 가능하게 된다',
    type: '3',
    icon: 100,
    size: 5,
  },
  {
    id: '522',
    name: '「마법검」사용 가능',
    description: '「마법검」이 사용 가능하게 된다',
    type: '3',
    icon: 100,
    size: 5,
  },
  {
    id: '523',
    name: '「음양술」사용 가능',
    description: '「음양술」이 사용 가능하게 된다',
    type: '3',
    icon: 100,
    size: 5,
  },
  {
    id: '524',
    name: '「마도과학」사용 가능',
    description: '「마도과학」이 사용 가능하게 된다',
    type: '3',
    icon: 100,
    size: 5,
  },
  {
    id: '525',
    name: '「연금술」사용 가능',
    description: '「연금술」이 사용 가능하게 된다',
    type: '3',
    icon: 100,
    size: 5,
  },
  {
    id: '526',
    name: '「마본술」사용 가능',
    description: '「마본술」이 사용 가능하게 된다',
    type: '3',
    icon: 100,
    size: 5,
  },
  {
    id: '527',
    name: '연속 마법',
    description: '마법 스킬이 2회 연속으로 발동한다',
    type: '3',
    icon: 100,
    size: 20,
  },
  {
    id: '528',
    name: '크로싱히르',
    description: '「백마법」의 위력이 마력에 의존하게 된다',
    type: '3',
    icon: 100,
    size: 2,
  },
  {
    id: '529',
    name: '테크니카르마기',
    description: '공격 마법의 위력이 손재주에 의존하게 된다',
    type: '3',
    icon: 100,
    size: 2,
  },
  {
    id: '530',
    name: '아탁크마기',
    description: '공격 마법의 위력이 공격력에 의존하게 된다',
    type: '3',
    icon: 100,
    size: 2,
  },
  {
    id: '531',
    name: '라핏드마기',
    description: '공격 마법의 위력이 민첩성에 의존하게 된다',
    type: '3',
    icon: 100,
    size: 2,
  },
  {
    id: '544',
    name: '방어력 10% 업',
    description: '방어력이 10% 올라간다',
    type: '4',
    icon: 98,
    size: 3,
  },
  {
    id: '545',
    name: '방어력 20% 업',
    description: '방어력이 20% 올라간다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '546',
    name: '방어력 30% 업',
    description: '방어력이 30% 올라간다',
    type: '4',
    icon: 98,
    size: 7,
  },
  {
    id: '547',
    name: '방어력 40% 업',
    description: '방어력이 40% 올라간다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '549',
    name: '정신력 10% 업',
    description: '정신력이 10% 올라간다',
    type: '4',
    icon: 98,
    size: 3,
  },
  {
    id: '550',
    name: '정신력 20% 업',
    description: '정신력이 20% 올라간다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '551',
    name: '정신력 30% 업',
    description: '정신력이 30% 올라간다',
    type: '4',
    icon: 98,
    size: 7,
  },
  {
    id: '552',
    name: '정신력 40% 업',
    description: '정신력이 40% 올라간다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '554',
    name: '회피율 10%',
    description: '물리 회피율이 10%가 된다',
    type: '4',
    icon: 98,
    size: 3,
  },
  {
    id: '555',
    name: '회피율 20%',
    description: '물리 회피율이 20%가 된다',
    type: '4',
    icon: 98,
    size: 6,
  },
  {
    id: '556',
    name: '회피율 30%',
    description: '물리 회피율이 30%가 된다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '558',
    name: '빈사시 회피율 업',
    description: '빈사시, 물리 회피율이 75% 올라간다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '559',
    name: '마법 회피율 10%',
    description: '마법 회피율이 10%가 된다',
    type: '4',
    icon: 98,
    size: 3,
  },
  {
    id: '560',
    name: '마법 회피율 20%',
    description: '마법 회피율이 20%가 된다',
    type: '4',
    icon: 98,
    size: 6,
  },
  {
    id: '561',
    name: '마법 회피율 30%',
    description: '마법 회피율이 30%가 된다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '563',
    name: '빈사 시마법 회피율 업',
    description: '빈사시, 마법 회피율이 75% 올라간다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '564',
    name: '오토 가드',
    description: '빈사시, 받는 물리 데미지를 반으로 한다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '565',
    name: '오토 배리어',
    description: '빈사시, 받는 마법 데미지를 반으로 한다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '566',
    name: '대방어',
    description: '방어의 효과가 올라간다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '567',
    name: '궁극 방어',
    description: '방어의 효과가 현격히 올라간다',
    type: '4',
    icon: 98,
    size: 6,
  },
  {
    id: '568',
    name: '마법 반사 10%',
    description: '마법을 10%의 확률로 반사한다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '569',
    name: '마법 반사 30%',
    description: '마법을 30%의 확률로 반사한다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '570',
    name: '마법 반사 50%',
    description: '마법을 50%의 확률로 반사한다',
    type: '4',
    icon: 98,
    size: 20,
  },
  {
    id: '572',
    name: '회심 무효',
    description: '적의 회심 공격을 완전하게 회피한다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '573',
    name: '여신의 가호',
    description: '전투 불능시, 한 번만 빈사 상태로 소생 한다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '574',
    name: '여신의 기적',
    description: '전투 불능시, 한 번 만여라 HP반 상태로 소생 한다',
    type: '4',
    icon: 98,
    size: 15,
  },
  {
    id: '575',
    name: '여신의 괴뢰',
    description: '전투 불능시, 한 번 만여라 HP완쾌 상태로 소생 한다',
    type: '4',
    icon: 98,
    size: 20,
  },
  {
    id: '576',
    name: '슬라임 보디',
    description: '50 이하의 피데미지를 무효화한다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '577',
    name: '소프트 보디',
    description: '200 이하의 피데미지를 무효화한다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '578',
    name: '슈프르보디',
    description: '500 이하의 피데미지를 무효화한다',
    type: '4',
    icon: 98,
    size: 15,
  },
  {
    id: '579',
    name: '나노 보디',
    description: '1000 이하의 피데미지를 무효화한다',
    type: '4',
    icon: 98,
    size: 25,
  },
  {
    id: '581',
    name: '가호의 육체',
    description: '빈사시, 100 이하의 피데미지를 무효화한다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '582',
    name: '은총의 육체',
    description: '빈사시, 300 이하의 피데미지를 무효화한다',
    type: '4',
    icon: 98,
    size: 20,
  },
  {
    id: '583',
    name: '기적의 육체',
    description: '빈사시, 1000 이하의 피데미지를 무효화한다',
    type: '4',
    icon: 98,
    size: 30,
  },
  {
    id: '585',
    name: '이를 악물어',
    description: 'HP가 30%이상 남아 있으면 전투 불능이 되지 않고 HP가 1남는다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '586',
    name: '매우 이를 악물어',
    description: 'HP가 20%이상 남아 있으면 전투 불능이 되지 않고 HP가 1남는다',
    type: '4',
    icon: 98,
    size: 15,
  },
  {
    id: '588',
    name: '집단의 방패',
    description: '전투 개시시, 집단이 대역이 되어 2회만 공격을 막는다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '589',
    name: '진동 장갑',
    description: '물리 데미지를 받으면 진동파로 반격',
    type: '4',
    icon: 98,
    size: 15,
  },
  {
    id: '590',
    name: '물리 데미지 경감',
    description: '물리 속성의 데미지를 3/4로 한다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '591',
    name: '물리 데미지 반감',
    description: '물리 속성의 데미지를 반으로 한다',
    type: '4',
    icon: 98,
    size: 20,
  },
  {
    id: '592',
    name: '물리 데미지 무효',
    description: '물리 속성의 데미지를 무효화한다',
    type: '4',
    icon: 98,
    size: 30,
  },
  {
    id: '594',
    name: '쾌락 데미지 경감',
    description: '쾌락 속성의 데미지를 3/4로 한다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '595',
    name: '쾌락 데미지 반감',
    description: '쾌락 속성의 데미지를 반으로 한다',
    type: '4',
    icon: 98,
    size: 20,
  },
  {
    id: '596',
    name: '쾌락 데미지 무효',
    description: '쾌락 속성의 데미지를 무효화한다',
    type: '4',
    icon: 98,
    size: 30,
  },
  {
    id: '598',
    name: '불길 데미지 경감',
    description: '염 속성의 데미지를 3/4로 한다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '599',
    name: '불길 데미지 반감',
    description: '염 속성의 데미지를 반으로 한다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '600',
    name: '불길 데미지 무효',
    description: '염 속성의 데미지를 무효화한다',
    type: '4',
    icon: 98,
    size: 15,
  },
  {
    id: '602',
    name: '얼음 데미지 경감',
    description: '얼음 속성의 데미지를 3/4로 한다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '603',
    name: '얼음 데미지 반감',
    description: '얼음 속성의 데미지를 반으로 한다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '604',
    name: '얼음 데미지 무효',
    description: '얼음 속성의 데미지를 무효화한다',
    type: '4',
    icon: 98,
    size: 15,
  },
  {
    id: '606',
    name: '번개 데미지 경감',
    description: '번개 속성의 데미지를 3/4로 한다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '607',
    name: '번개 데미지 반감',
    description: '번개 속성의 데미지를 반으로 한다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '608',
    name: '번개 데미지 무효',
    description: '번개 속성의 데미지를 무효화한다',
    type: '4',
    icon: 98,
    size: 15,
  },
  {
    id: '609',
    name: '번개 데미지 흡수',
    description: '번개 속성의 데미지를 흡수한다',
    type: '4',
    icon: 98,
    size: 20,
  },
  {
    id: '610',
    name: '바람 데미지 경감',
    description: '풍속성의 데미지를 3/4로 한다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '611',
    name: '바람 데미지 반감',
    description: '풍속성의 데미지를 반으로 한다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '612',
    name: '바람 데미지 무효',
    description: '풍속성의 데미지를 무효화한다',
    type: '4',
    icon: 98,
    size: 15,
  },
  {
    id: '613',
    name: '바람 데미지 흡수',
    description: '풍속성의 데미지를 흡수한다',
    type: '4',
    icon: 98,
    size: 20,
  },
  {
    id: '614',
    name: '흙 데미지 경감',
    description: '흙 속성의 데미지를 3/4로 한다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '615',
    name: '흙 데미지 반감',
    description: '흙 속성의 데미지를 반으로 한다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '616',
    name: '흙 데미지 무효',
    description: '흙 속성의 데미지를 무효화한다',
    type: '4',
    icon: 98,
    size: 15,
  },
  {
    id: '618',
    name: '물 데미지 경감',
    description: '물 속성의 데미지를 3/4로 한다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '619',
    name: '물 데미지 반감',
    description: '물 속성의 데미지를 반으로 한다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '620',
    name: '물 데미지 무효',
    description: '물 속성의 데미지를 무효화한다',
    type: '4',
    icon: 98,
    size: 15,
  },
  {
    id: '621',
    name: '물 데미지 흡수',
    description: '물 속성의 데미지를 흡수한다',
    type: '4',
    icon: 98,
    size: 20,
  },
  {
    id: '622',
    name: '성데미지 경감',
    description: '성속성의 데미지를 3/4로 한다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '623',
    name: '성데미지 반감',
    description: '성속성의 데미지를 반으로 한다',
    type: '4',
    icon: 98,
    size: 20,
  },
  {
    id: '624',
    name: '성데미지 무효',
    description: '성속성의 데미지를 무효화한다',
    type: '4',
    icon: 98,
    size: 30,
  },
  {
    id: '626',
    name: '어둠 데미지 경감',
    description: '어둠 속성의 데미지를 3/4로 한다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '627',
    name: '어둠 데미지 반감',
    description: '어둠 속성의 데미지를 반으로 한다',
    type: '4',
    icon: 98,
    size: 20,
  },
  {
    id: '628',
    name: '어둠 데미지 무효',
    description: '어둠 속성의 데미지를 무효화한다',
    type: '4',
    icon: 98,
    size: 30,
  },
  {
    id: '630',
    name: '음파 데미지 경감',
    description: '음파 속성의 데미지를 3/4로 한다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '631',
    name: '음파 데미지 반감',
    description: '음파 속성의 데미지를 반으로 한다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '632',
    name: '음파 데미지 무효',
    description: '음파 속성의 데미지를 무효화한다',
    type: '4',
    icon: 98,
    size: 15,
  },
  {
    id: '633',
    name: '음파 데미지 흡수',
    description: '음파 속성의 데미지를 흡수한다',
    type: '4',
    icon: 98,
    size: 20,
  },
  {
    id: '634',
    name: '바이오 데미지 경감',
    description: '바이오 속성의 데미지를 3/4로 한다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '635',
    name: '바이오 데미지 반감',
    description: '바이오 속성의 데미지를 반으로 한다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '636',
    name: '바이오 데미지 무효',
    description: '바이오 속성의 데미지를 무효화한다',
    type: '4',
    icon: 98,
    size: 15,
  },
  {
    id: '638',
    name: '속성 데미지 경감',
    description: '성과 어둠 이외의 속성 데미지를 3/4로 한다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '639',
    name: '속성 데미지 반감',
    description: '성과 어둠 이외의 속성 데미지를 반으로 한다',
    type: '4',
    icon: 98,
    size: 20,
  },
  {
    id: '640',
    name: '속성 데미지 무효',
    description: '성과 어둠 이외의 속성 데미지를 무효화한다',
    type: '4',
    icon: 98,
    size: 30,
  },
  {
    id: '642',
    name: '능력 약체 회피',
    description: '능력 약체를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '643',
    name: '능력 약체 무효',
    description: '능력 약체를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '644',
    name: '즉사 회피',
    description: '즉사 공격을 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '645',
    name: '즉사 무효',
    description: '즉사 공격을 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '646',
    name: '승천 회피',
    description: '승천 공격을 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '647',
    name: '승천 무효',
    description: '승천 공격을 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '648',
    name: '절정 회피',
    description: '절정 공격을 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '649',
    name: '절정 무효',
    description: '절정 공격을 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '650',
    name: '전즉사계 무효',
    description: '즉사·승천·절정 공격을 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '651',
    name: '구속 회피',
    description: '구속 공격을 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 10,
  },
  {
    id: '652',
    name: '구속 무효',
    description: '구속 공격을 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 20,
  },
  {
    id: '653',
    name: '독 회피',
    description: '독 상태를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '654',
    name: '독 무효',
    description: '독 상태를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '655',
    name: '어둠 회피',
    description: '어둠 상태를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '656',
    name: '어둠 무효',
    description: '어둠 상태를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '657',
    name: '침묵 회피',
    description: '침묵 상태를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '658',
    name: '침묵 무효',
    description: '침묵 상태를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '659',
    name: '혼란 회피',
    description: '혼란 상태를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '660',
    name: '혼란 무효',
    description: '혼란 상태를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '661',
    name: '수면 회피',
    description: '수면 상태를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '662',
    name: '수면 무효',
    description: '수면 상태를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '663',
    name: '마비 회피',
    description: '마비 상태를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '664',
    name: '마비 무효',
    description: '마비 상태를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '665',
    name: '반 회피',
    description: '반 상태를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '666',
    name: '반 무효',
    description: '반 상태를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '667',
    name: '프리즈 회피',
    description: '프리즈 상태를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '668',
    name: '프리즈 무효',
    description: '프리즈 상태를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '669',
    name: '쇼크 회피',
    description: '쇼크 상태를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '670',
    name: '쇼크 무효',
    description: '쇼크 상태를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '671',
    name: '슬로우 회피',
    description: '슬로우 상태를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '672',
    name: '슬로우 무효',
    description: '슬로우 상태를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '673',
    name: '스톱 회피',
    description: '스톱 상태를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '674',
    name: '스톱 무효',
    description: '스톱 상태를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '675',
    name: '미니맘 회피',
    description: '미니맘 상태를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '676',
    name: '미니맘 무효',
    description: '미니맘 상태를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '677',
    name: '좀비 회피',
    description: '좀비 상태를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '678',
    name: '좀비 무효',
    description: '좀비 상태를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '679',
    name: '석화 회피',
    description: '석화 상태를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '680',
    name: '석화 무효',
    description: '석화 상태를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '681',
    name: '소화 회피',
    description: '소화 상태를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '682',
    name: '소화 무효',
    description: '소화 상태를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '683',
    name: '스턴 회피',
    description: '스턴 상태를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '684',
    name: '스턴 무효',
    description: '스턴 상태를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '685',
    name: '미끈미끈 회피',
    description: '미끈미끈 상태를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '686',
    name: '미끈미끈 무효',
    description: '미끈미끈 상태를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '687',
    name: '민감 회피',
    description: '민감 상태를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '688',
    name: '민감 무효',
    description: '민감 상태를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '689',
    name: '황홀 회피',
    description: '황홀 상태를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '690',
    name: '황홀 무효',
    description: '황홀 상태를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '691',
    name: '유혹 회피',
    description: '유혹 상태를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '692',
    name: '유혹 무효',
    description: '유혹 상태를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '693',
    name: '실금 회피',
    description: '실금 상태를 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 2,
  },
  {
    id: '694',
    name: '실금 무효',
    description: '실금 상태를 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 4,
  },
  {
    id: '695',
    name: '전상태 이상 회피',
    description: '모든 상태 이상을 50%의 확률로 무효화한다',
    type: '4',
    icon: 98,
    size: 15,
  },
  {
    id: '696',
    name: '전상태 이상 무효',
    description: '모든 상태 이상을 완전하게 무효화한다',
    type: '4',
    icon: 98,
    size: 30,
  },
  {
    id: '697',
    name: '「무도복」장비 가능',
    description: '「옷」 「무도복」이 장비 가능하게 된다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '698',
    name: '「갑옷」장비 가능',
    description: '「갑옷」 「중갑」 「흉갑」이 장비 가능하게 된다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '699',
    name: '「로브」장비 가능',
    description: '「로브」 「드레스」 「엷은옷」이 장비 가능하게 된다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '700',
    name: '「투구」장비 가능',
    description: '「투구」 「중투구」가 장비 가능하게 된다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '701',
    name: '「마법모」장비 가능',
    description: '「모자」 「마법모」 「고급모」가 장비 가능하게 된다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '702',
    name: '「방패」장비 가능',
    description: '「경방패」 「방패」 「중방패」가 장비 가능하게 된다',
    type: '4',
    icon: 98,
    size: 5,
  },
  {
    id: '708',
    name: '매턴 HP 5% 회복',
    description: '턴 마다 HP가 5% 회복 한다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '709',
    name: '매턴 HP 10% 회복',
    description: '턴 마다 HP가 10% 회복 한다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '710',
    name: '매턴 HP 20% 회복',
    description: '턴 마다 HP가 20% 회복 한다',
    type: '5',
    icon: 99,
    size: 20,
  },
  {
    id: '711',
    name: '매턴 HP 30% 회복',
    description: '턴 마다 HP가 30% 회복 한다',
    type: '5',
    icon: 99,
    size: 30,
  },
  {
    id: '713',
    name: '매턴 MP 1% 회복',
    description: '턴 마다 MP가 1% 회복 한다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '714',
    name: '매턴 MP 2% 회복',
    description: '턴 마다 MP가 2% 회복 한다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '715',
    name: '매턴 MP 4% 회복',
    description: '턴 마다 MP가 4% 회복 한다',
    type: '5',
    icon: 99,
    size: 20,
  },
  {
    id: '716',
    name: '매턴 MP 8% 회복',
    description: '턴 마다 MP가 8% 회복 한다',
    type: '5',
    icon: 99,
    size: 30,
  },
  {
    id: '718',
    name: '매턴 SP5% 회복',
    description: '턴 마다 SP가 5% 회복 한다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '719',
    name: '매턴 SP 10% 회복',
    description: '턴 마다 SP가 10% 회복 한다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '720',
    name: '매턴 SP 20% 회복',
    description: '턴 마다 SP가 20% 회복 한다',
    type: '5',
    icon: 99,
    size: 20,
  },
  {
    id: '721',
    name: '매턴 SP 30% 회복',
    description: '턴 마다 SP가 30% 회복 한다',
    type: '5',
    icon: 99,
    size: 30,
  },
  {
    id: '723',
    name: 'SP차지 2배',
    description: 'SP의 회복량이 2배가 된다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '724',
    name: 'SP차지 3배',
    description: 'SP의 회복량이 3배가 된다',
    type: '5',
    icon: 99,
    size: 20,
  },
  {
    id: '726',
    name: '약의 지식 1',
    description: '회복 아이템의 효과가 1.5배가 된다',
    type: '5',
    icon: 99,
    size: 3,
  },
  {
    id: '727',
    name: '약의 지식 2',
    description: '회복 아이템의 효과가 2배가 된다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '728',
    name: '약의 지식 3',
    description: '회복 아이템의 효과가 3배가 된다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '729',
    name: '궁극 약효',
    description: '회복 아이템의 효과가 5배가 된다',
    type: '5',
    icon: 99,
    size: 15,
  },
  {
    id: '730',
    name: '대사 업',
    description: '회복 마법이나 아이템을 받았을 때의 효과가 2배가 된다',
    type: '5',
    icon: 99,
    size: 3,
  },
  {
    id: '731',
    name: '초대사',
    description: '회복 마법이나 아이템을 받았을 때의 효과가 3배가 된다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '732',
    name: '궁극 대사',
    description: '회복 마법이나 아이템을 받았을 때의 효과가 5배가 된다',
    type: '5',
    icon: 99,
    size: 8,
  },
  {
    id: '733',
    name: '어필',
    description: '전투시, 적에게 노려지는 확률이 오른다',
    type: '5',
    icon: 99,
    size: 1,
  },
  {
    id: '734',
    name: '초 어필',
    description: '전투시, 적에게 노려지는 확률이 크게 오른다',
    type: '5',
    icon: 99,
    size: 3,
  },
  {
    id: '735',
    name: '하인드',
    description: '전투시, 적에게 노려지는 확률이 내린다',
    type: '5',
    icon: 99,
    size: 1,
  },
  {
    id: '736',
    name: '초 하인드',
    description: '전투시, 적에게 노려지는 확률이 크게 내린다',
    type: '5',
    icon: 99,
    size: 3,
  },
  {
    id: '737',
    name: '빈사시 2회 행동',
    description: '빈사시, 1 턴에 2회 행동할 수 있다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '740',
    name: '버서커',
    description: '항상 버서크 상태가 된다',
    type: '5',
    icon: 99,
    size: 1,
  },
  {
    id: '741',
    name: '하이 버서커',
    description: '항상 버서크·2회 행동 상태가 된다',
    type: '5',
    icon: 99,
    size: 3,
  },
  {
    id: '742',
    name: '좀비 체질',
    description: '회복 마법으로 데미지를 받아, 바이오 속성으로 회복 한다 또 즉사 마법으로 HP가 완전 회복 한다',
type: '5',
    icon: 99,
    size: 1,
  },
  {
    id: '744',
    name: '기습 무효',
    description: '기습을 무효로 한다',
    type: '5',
    icon: 99,
    size: 3,
  },
  {
    id: '745',
    name: '선제 공격 업',
    description: '선제 공격이 발생하는 확률이 오른다',
    type: '5',
    icon: 99,
    size: 3,
  },
  {
    id: '746',
    name: '전투 개시시 SP증가',
    description: '전투 개시시의 SP가 증가한다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '747',
    name: '전투 개시시 SP최대',
    description: '전투 개시시의 SP가 최대가 된다',
    type: '5',
    icon: 99,
    size: 20,
  },
  {
    id: '748',
    name: '전투후 잠시 쉼',
    description: '전투후, HP와 MP를 소회복',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '749',
    name: '전투후 오야스미지',
    description: '전투후, HP와 MP를 안회복',
    type: '5',
    icon: 99,
    size: 15,
  },
  {
    id: '752',
    name: '경험치 1.5배',
    description: '획득하는 경험치가 1.5배가 된다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '753',
    name: '경험치 2배',
    description: '획득하는 경험치가 2배가 된다',
    type: '5',
    icon: 99,
    size: 20,
  },
  {
    id: '754',
    name: '경험치 3배',
    description: '획득하는 경험치가 3배가 된다',
    type: '5',
    icon: 99,
    size: 30,
  },
  {
    id: '755',
    name: '직업 경험치 1.5배',
    description: '획득하는 직업 경험치가 1.5배가 된다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '756',
    name: '직업 경험치 2배',
    description: '획득하는 직업 경험치가 2배가 된다',
    type: '5',
    icon: 99,
    size: 20,
  },
  {
    id: '757',
    name: '직업 경험치 3배',
    description: '획득하는 직업 경험치가 3배가 된다',
    type: '5',
    icon: 99,
    size: 30,
  },
  {
    id: '758',
    name: '획득 골드 1.5배',
    description: '획득하는 골드가 1.5배가 된다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '759',
    name: '획득 골드 2배',
    description: '획득하는 골드가 2배가 된다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '760',
    name: '획득 골드 3배',
    description: '획득하는 골드가 3배가 된다',
    type: '5',
    icon: 99,
    size: 15,
  },
  {
    id: '761',
    name: '아이템 드롭 1.5배',
    description: '적이 아이템을 떨어뜨리는 확률이 1.5배가 된다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '762',
    name: '아이템 드롭 2배',
    description: '적이 아이템을 떨어뜨리는 확률이 2배가 된다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '763',
    name: '아이템 드롭 3배',
    description: '적이 아이템을 떨어뜨리는 확률이 3배가 된다',
    type: '5',
    icon: 99,
    size: 15,
  },
  {
    id: '764',
    name: '도적 해정 1',
    description: '파랑의 보물상자가 열리게 된다',
    type: '5',
    icon: 99,
    size: 3,
  },
  {
    id: '765',
    name: '도적 해정 2',
    description: '파랑·초록의 보물상자가 열리게 된다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '766',
    name: '도적 해정 3',
    description: '파랑·초록·플라티나의 보물상자가 열리게 된다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '767',
    name: '동료 확률 1.5배',
    description: '몬스터가 동료가 되는 확률이 1.5배가 된다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '768',
    name: '동료 확률 2배',
    description: '몬스터가 동료가 되는 확률이 2배가 된다',
    type: '5',
    icon: 99,
    size: 20,
  },
  {
    id: '769',
    name: '동료 확률 3배',
    description: '몬스터가 동료가 되는 확률이 3배가 된다',
    type: '5',
    icon: 99,
    size: 30,
  },
  {
    id: '770',
    name: '훔치는 확률 업 1.5배',
    description: '적으로부터 아이템을 훔칠 수 있는 확률이 1.5배가 된다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '771',
    name: '훔치는 확률 업 2배',
    description: '적으로부터 아이템을 훔칠 수 있는 확률이 2배가 된다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '772',
    name: '훔치는 확률 업 3배',
    description: '적으로부터 아이템을 훔칠 수 있는 확률이 3배가 된다',
    type: '5',
    icon: 99,
    size: 15,
  },
  {
    id: '773',
    name: '춤성공 확률 업',
    description: '춤사용시의 스테이터스 이상 발생율이 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '774',
    name: '노래 성공 확률 업',
    description: '노래 사용시의 스테이터스 이상 발생율이 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '775',
    name: '음 기술 성공 확률 업',
    description: '음 기술 사용시의 스테이터스 이상 발생율이 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '776',
    name: '마안성공 확률 업',
    description: '마안사용시의 스테이터스 이상 발생율이 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '777',
    name: '화분 성공 확률 업',
    description: '화분 사용시의 스테이터스 이상 발생율이 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '779',
    name: '어둠의 계약',
    description: '어둠 속성 스킬을 사용했을 때의 HP소비가 반감한다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '780',
    name: '어둠의 지배자',
    description: '어둠 속성 스킬을 사용했을 때의 HP소비가 없어진다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '781',
    name: '숲 강화',
    description: '숲에서의 전투시, 능력치가 20% 올라간다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '782',
    name: '숲 초강화',
    description: '숲에서의 전투시, 능력치가 40% 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '783',
    name: '사막 강화',
    description: '사막에서의 전투시, 능력치가 20% 올라간다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '784',
    name: '사막 초강화',
    description: '사막에서의 전투시, 능력치가 40% 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '785',
    name: '해 강화',
    description: '바다에서의 전투시, 능력치가 20% 올라간다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '786',
    name: '해 초강화',
    description: '바다에서의 전투시, 능력치가 40% 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '787',
    name: '심해 강화',
    description: '심해에서의 전투시, 능력치가 20% 올라간다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '788',
    name: '심해 초강화',
    description: '심해에서의 전투시, 능력치가 40% 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '789',
    name: '동굴 강화',
    description: '동굴에서의 전투시, 능력치가 20% 올라간다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '790',
    name: '동굴 초강화',
    description: '동굴에서의 전투시, 능력치가 40% 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '791',
    name: '시가 강화',
    description: '시가에서의 전투시, 능력치가 20% 올라간다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '792',
    name: '시가 초강화',
    description: '시가에서의 전투시, 능력치가 40% 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '793',
    name: '마루 데미지 반감',
    description: '독소나 배리어로 받는 이동 데미지를 반감한다',
    type: '5',
    icon: 99,
    size: 2,
  },
  {
    id: '794',
    name: '마루 데미지 무효',
    description: '독소나 배리어로 받는 이동 데미지를 무효화한다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '795',
    name: '인카운터 반',
    description: '적과 조우하는 확률이 반이 된다',
    type: '5',
    icon: 99,
    size: 1,
  },
  {
    id: '796',
    name: '인카운터 없음',
    description: '적과 조우하지 않게 된다(특수한 적은 제외하다)',
    type: '5',
    icon: 99,
    size: 2,
  },
  {
    id: '797',
    name: '인카운터 2배',
    description: '적과 조우하는 확률이 2배가 된다',
    type: '5',
    icon: 99,
    size: 1,
  },
  {
    id: '798',
    name: '인카운터 5배',
    description: '적과 조우하는 확률이 5배가 된다',
    type: '5',
    icon: 99,
    size: 2,
  },
  {
    id: '799',
    name: '목숨을 걺의 수행',
    description: '최대 HP가 반이 되지만, 획득 경험치가 1.5배가 된다',
    type: '5',
    icon: 99,
    size: 1,
  },
  {
    id: '800',
    name: '빈사의 수행',
    description: '최대 HP가 1/100가 되지만, 획득 경험치가 2배가 된다',
    type: '5',
    icon: 99,
    size: 1,
  },
  {
    id: '801',
    name: '쾌락의 포로',
    description: '쾌락 데미지가 2배가 되지만, 획득 경험치가 50% 올라간다',
    type: '5',
    icon: 99,
    size: 1,
  },
  {
    id: '802',
    name: '경험치 우선 수행',
    description: '획득 경험치가 1.5배가 되지만, 획득 직업 경험치는 반이 된다',
    type: '5',
    icon: 99,
    size: 1,
  },
  {
    id: '803',
    name: '경험치 전념 수행',
    description: '획득 경험치가 2배가 되지만, 직업 경험치는 얻을 수 없다',
    type: '5',
    icon: 99,
    size: 1,
  },
  {
    id: '804',
    name: '직업 우선 수행',
    description: '획득 직업 경험치가 1.5배가 되지만, 획득 경험치는 반이 된다',
    type: '5',
    icon: 99,
    size: 3,
  },
  {
    id: '805',
    name: '직업 전념 수행',
    description: '획득 직업 경험치가 2배가 되지만, 경험치는 얻을 수 없다',
    type: '5',
    icon: 99,
    size: 3,
  },
  {
    id: '806',
    name: '놀아 좋아',
    description: '획득 경험치가 1.5배가 되지만, 전투 나카가치손에 노는 것이 있다',
    type: '5',
    icon: 99,
    size: 1,
  },
  {
    id: '807',
    name: '마 기술 부스터',
    description: '「마 기술」에 의한 데미지가 15% 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '808',
    name: '마 기술 하이 부스터',
    description: '「마 기술」에 의한 데미지가 30% 올라간다',
    type: '5',
    icon: 99,
    size: 20,
  },
  {
    id: '809',
    name: '마 기술 액스 부스터',
    description: '「마 기술」에 의한 데미지가 50% 올라간다',
    type: '5',
    icon: 99,
    size: 30,
  },
  {
    id: '810',
    name: '해 기술 부스터',
    description: '「바다 기술」에 의한 데미지가 15% 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '811',
    name: '해 기술 하이 부스터',
    description: '「바다 기술」에 의한 데미지가 30% 올라간다',
    type: '5',
    icon: 99,
    size: 20,
  },
  {
    id: '813',
    name: '자연감응 부스터',
    description: '「자연감응」에 의한 데미지가 15% 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '814',
    name: '자연감응 하이 부스터',
    description: '「자연감응」에 의한 데미지가 30% 올라간다',
    type: '5',
    icon: 99,
    size: 20,
  },
  {
    id: '815',
    name: '자연감응 액스 부스터',
    description: '「자연감응」에 의한 데미지가 50% 올라간다',
    type: '5',
    icon: 99,
    size: 30,
  },
  {
    id: '816',
    name: '점액 기술 부스터',
    description: '「점액 기술」에 의한 데미지가 15% 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '817',
    name: '점액 기술 하이 부스터',
    description: '「점액 기술」에 의한 데미지가 30% 올라간다',
    type: '5',
    icon: 99,
    size: 20,
  },
  {
    id: '819',
    name: '짐승 기술 부스터',
    description: '「짐승 기술」에 의한 데미지가 15% 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '820',
    name: '짐승 기술 하이 부스터',
    description: '「짐승 기술」에 의한 데미지가 30% 올라간다',
    type: '5',
    icon: 99,
    size: 20,
  },
  {
    id: '822',
    name: '뱀 기술 부스터',
    description: '「뱀 기술」에 의한 데미지가 15% 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '823',
    name: '뱀 기술 하이 부스터',
    description: '「뱀 기술」에 의한 데미지가 30% 올라간다',
    type: '5',
    icon: 99,
    size: 20,
  },
  {
    id: '825',
    name: '촉수 기술 부스터',
    description: '「촉수 기술」에 의한 데미지가 15% 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '826',
    name: '촉수 기술 하이 부스터',
    description: '「촉수 기술」에 의한 데미지가 30% 올라간다',
    type: '5',
    icon: 99,
    size: 20,
  },
  {
    id: '828',
    name: '날개 기술 부스터',
    description: '「날개 기술」에 의한 데미지가 15% 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '829',
    name: '날개 기술 하이 부스터',
    description: '「날개 기술」에 의한 데미지가 30% 올라간다',
    type: '5',
    icon: 99,
    size: 20,
  },
  {
    id: '831',
    name: '브레스 부스터',
    description: '「브레스」에 의한 데미지가 15% 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '832',
    name: '브레스 하이 부스터',
    description: '「브레스」에 의한 데미지가 30% 올라간다',
    type: '5',
    icon: 99,
    size: 20,
  },
  {
    id: '834',
    name: '충 기술 부스터',
    description: '「벌레 기술」에 의한 데미지가 15% 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '835',
    name: '충 기술 하이 부스터',
    description: '「벌레 기술」에 의한 데미지가 30% 올라간다',
    type: '5',
    icon: 99,
    size: 20,
  },
  {
    id: '837',
    name: '식물 기술 부스터',
    description: '「식물 기술」에 의한 데미지가 15% 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '838',
    name: '식물 기술 하이 부스터',
    description: '「식물 기술」에 의한 데미지가 30% 올라간다',
    type: '5',
    icon: 99,
    size: 20,
  },
  {
    id: '840',
    name: '시체 기술 부스터',
    description: '「시체 기술」에 의한 데미지가 15% 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '841',
    name: '시체 기술 하이 부스터',
    description: '「시체 기술」에 의한 데미지가 30% 올라간다',
    type: '5',
    icon: 99,
    size: 20,
  },
  {
    id: '843',
    name: '개조 기술 부스터',
    description: '「개조 기술」에 의한 데미지가 15% 올라간다',
    type: '5',
    icon: 99,
    size: 10,
  },
  {
    id: '844',
    name: '개조 기술 하이 부스터',
    description: '「개조 기술」에 의한 데미지가 30% 올라간다',
    type: '5',
    icon: 99,
    size: 20,
  },
  {
    id: '848',
    name: '「마 기술」사용 가능',
    description: '「마 기술」이 사용 가능하게 된다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '849',
    name: '「바다 기술」사용 가능',
    description: '「바다 기술」이 사용 가능하게 된다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '850',
    name: '「점액 기술」사용 가능',
    description: '「점액 기술」이 사용 가능하게 된다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '851',
    name: '「짐승 기술」사용 가능',
    description: '「짐승 기술」이 사용 가능하게 된다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '852',
    name: '「뱀 기술」사용 가능',
    description: '「뱀 기술」이 사용 가능하게 된다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '853',
    name: '「촉수 기술」사용 가능',
    description: '「촉수 기술」이 사용 가능하게 된다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '854',
    name: '「날개 기술」사용 가능',
    description: '「날개 기술」이 사용 가능하게 된다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '855',
    name: '「벌레 기술」사용 가능',
    description: '「벌레 기술」이 사용 가능하게 된다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '856',
    name: '「식물 기술」사용 가능',
    description: '「식물 기술」이 사용 가능하게 된다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '857',
    name: '「시체 기술」사용 가능',
    description: '「시체 기술」이 사용 가능하게 된다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '858',
    name: '「개조 기술」사용 가능',
    description: '「개조 기술」이 사용 가능하게 된다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '859',
    name: '「자연감응」사용 가능',
    description: '「자연감응」이 사용 가능하게 된다',
    type: '5',
    icon: 99,
    size: 5,
  },
  {
    id: '860',
    name: '「브레스」사용 가능',
    description: '「브레스」가 사용 가능하게 된다',
    type: '5',
    icon: 99,
    size: 5,
  },
];
